# Site settings
author: Renee
title: Renee's Dev Blog
header-img: img/home-bg.png
email: reneenordholm@gmail.com
copyright_name: Renee
description: > # this means to ignore newlines until "baseurl:"
  Thoughts as I learn to code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  reneenordholm

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
